// Code generated by hertz generator.

package task

import (
	"github.com/cloudwego/hertz/pkg/app"
	"nodolist/pkg/utils/jwt"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtaskMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _changetaskstatusMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _tasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _shownotdotaskMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _showdonetaskMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}
